#!/usr/bin/env python3
"""Generate package versions from version.json; --check verifies checked-in outputs."""
from __future__ import annotations
import argparse
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
CONFIG = json.loads((ROOT / "version.json").read_text(encoding="utf-8"))
VERSION = CONFIG["version"]
PYTHON_VERSION = re.sub(r"-rc\.(\d+)$", r"rc\1", VERSION)
TAG = "v" + VERSION
RUNTIME_VERSION = CONFIG["runtime"]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = {
        ROOT / "version.go": f'// Code generated by scripts/version.py; DO NOT EDIT.\npackage oneocr\n\nconst Version = "{VERSION}"\nconst ReleaseTag = "{TAG}"\nconst ManagedRuntimeVersion = "{RUNTIME_VERSION}"\n',
        ROOT / "python/src/oneocr_native/_version.py": f'# Generated by scripts/version.py; do not edit.\n__version__ = "{PYTHON_VERSION}"\nRELEASE_TAG = "{TAG}"\nRUNTIME_VERSION = "{RUNTIME_VERSION}"\n',
    }
    for path, text in files.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"stale generated version: {path}")
        else:
            path.write_text(text, encoding="utf-8")
if __name__ == "__main__":
    main()
